#!/usr/bin/env python3
"""Build the self-contained ID Protect Offline HTML file.

The editable source stays split under src/. This script inlines the CSS and
application JavaScript into one index.html that can be opened directly from
file:// without a local server, CDN, external font, or runtime subresource.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = ROOT / "src" / "index.template.html"
STYLE = ROOT / "src" / "styles.css"
APP = ROOT / "src" / "app.js"
LOCALES_DIR = ROOT / "src" / "locales"
DEFAULT_OUTPUT = ROOT / "index.html"

REPLACEMENTS = {
    "{{IDPROTECT_CSS}}": STYLE,
    "{{IDPROTECT_APP_JS}}": APP,
}

REQUIRED_LOCALES = ("en", "de", "fr")


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise SystemExit(f"Missing build input: {path.relative_to(ROOT)}") from exc


def inline_css(text: str) -> str:
    if "</style" in text.lower():
        raise SystemExit("Refusing to inline CSS containing a closing </style tag")
    return text.rstrip() + "\n"


def inline_script(text: str) -> str:
    return text.replace("</script", "<\\/script").rstrip() + "\n"


def load_locale_maps() -> dict[str, dict[str, str]]:
    locale_maps: dict[str, dict[str, str]] = {}
    for locale in REQUIRED_LOCALES:
        path = LOCALES_DIR / f"{locale}.json"
        try:
            data = json.loads(read_text(path))
        except json.JSONDecodeError as exc:
            raise SystemExit(f"Invalid locale JSON in {path.relative_to(ROOT)}: {exc}") from exc

        if not isinstance(data, dict):
            raise SystemExit(f"Locale file must contain an object: {path.relative_to(ROOT)}")

        invalid_keys = [key for key in data if not isinstance(key, str) or not isinstance(data[key], str)]
        if invalid_keys:
            raise SystemExit(
                f"Locale file must be a flat string map: {path.relative_to(ROOT)} "
                f"({', '.join(map(str, invalid_keys[:5]))})"
            )
        locale_maps[locale] = data

    reference_keys = set(locale_maps["en"])
    for locale, data in locale_maps.items():
        keys = set(data)
        missing = sorted(reference_keys - keys)
        extra = sorted(keys - reference_keys)
        if missing or extra:
            details = []
            if missing:
                details.append(f"missing: {', '.join(missing[:10])}")
            if extra:
                details.append(f"extra: {', '.join(extra[:10])}")
            raise SystemExit(f"Locale key mismatch in {locale}.json ({'; '.join(details)})")

    return locale_maps


def build_locales_script(locale_maps: dict[str, dict[str, str]]) -> str:
    payload = json.dumps(locale_maps, ensure_ascii=False, separators=(",", ":"))
    return f"/* Embedded locale resources for ID Protect Offline. */\nwindow.IDPROTECT_EMBEDDED_LOCALES = {payload};\n"


def build_html(locale_script: str) -> str:
    html = read_text(TEMPLATE)
    if "{{IDPROTECT_LOCALES_JS}}" not in html:
        raise SystemExit("Template marker missing: {{IDPROTECT_LOCALES_JS}}")
    html = html.replace("{{IDPROTECT_LOCALES_JS}}", inline_script(locale_script), 1)

    for marker, path in REPLACEMENTS.items():
        if marker not in html:
            raise SystemExit(f"Template marker missing: {marker}")
        text = read_text(path)
        replacement = inline_css(text) if path.suffix == ".css" else inline_script(text)
        html = html.replace(marker, replacement, 1)

    leftover = [marker for marker in (*REPLACEMENTS, "{{IDPROTECT_LOCALES_JS}}") if marker in html]
    if leftover:
        raise SystemExit(f"Unreplaced template marker(s): {', '.join(leftover)}")

    note = (
        "<!--\n"
        "  Generated by tools/build.py. Edit src/* or src/locales/*, then rebuild.\n"
        "  This file is intentionally self-contained for offline file:// use.\n"
        "-->\n"
    )
    if html.startswith("<!doctype html>"):
        html = html.replace("<!doctype html>\n", "<!doctype html>\n" + note, 1)
    else:
        html = note + html

    validate_generated_html(html)
    return html


def validate_generated_html(html: str) -> None:
    disallowed = {
        "<script src>": re.compile(r"<script\b[^>]*\bsrc\s*=", re.IGNORECASE),
        "<link>": re.compile(r"<link\b", re.IGNORECASE),
        "<iframe>": re.compile(r"<iframe\b", re.IGNORECASE),
        "<object>": re.compile(r"<object\b", re.IGNORECASE),
        "<embed>": re.compile(r"<embed\b", re.IGNORECASE),
    }
    found = [name for name, pattern in disallowed.items() if pattern.search(html)]
    if found:
        raise SystemExit(f"Generated HTML contains disallowed external-loading tag(s): {', '.join(found)}")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build self-contained index.html")
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Output HTML path, default: index.html",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Do not write; fail if the output file is not up to date",
    )
    args = parser.parse_args(argv)

    output = args.output if args.output.is_absolute() else ROOT / args.output
    generated = build_html(build_locales_script(load_locale_maps()))

    if args.check:
        existing = output.read_text(encoding="utf-8") if output.exists() else ""
        if existing != generated:
            print(f"{output.relative_to(ROOT)} is not up to date", file=sys.stderr)
            print(f"expected sha256 {sha256_text(generated)}", file=sys.stderr)
            print(f"existing sha256 {sha256_text(existing)}", file=sys.stderr)
            return 1
        return 0

    output.write_text(generated, encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT)} ({len(generated):,} bytes)")
    print(f"sha256 {sha256_text(generated)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
